version: "3.8"

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - KEYCLOAK_IMPORT=/keycloak/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm.json:/keycloak/realm.json

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres:
