spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8081/auth/realms/Study/protocol/openid-connect/token/introspect
          introspection-client-id: springboot-study-oauth
          introspection-client-secret: SIXe65im12CNtokb8GKLeYLqCzVFA5rq
  redis:
    host: localhost
    port: 6379

token:
  cache:
    expiresInSeconds: 300
